import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const sdkRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(sdkRoot, '..');
const backendRoot = path.join(repoRoot, 'backend');
const openApiPath = path.join(backendRoot, 'openapi-v2.json');
const errorCodesPath = path.join(
  backendRoot,
  'src',
  'common',
  'config',
  'error-codes.json',
);
const packageJsonPath = path.join(sdkRoot, 'package.json');
const generatedRoot = path.join(sdkRoot, 'src', 'generated');
const metadataPath = path.join(sdkRoot, 'src', 'metadata.ts');
const errorsPath = path.join(sdkRoot, 'src', 'errors.ts');
const indexPath = path.join(sdkRoot, 'src', 'index.ts');

function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, 'utf8'));
}

function toConstObject(entries) {
  return JSON.stringify(entries, null, 2)
    .replace(/"([A-Za-z0-9_]+)":/g, '$1:')
    .replace(/"([A-Z_0-9]+)"/g, "'$1'");
}

function writeRuntimeFiles(spec, pkg, errorConfig) {
  const apiVersion = String(spec.info?.version ?? '0.0.0');
  const packageVersion = String(pkg.version ?? '0.0.0');
  const specMajor = Number.parseInt(apiVersion.split('.')[0] ?? apiVersion, 10);
  const packageMajor = Number.parseInt(
    packageVersion.split('.')[0] ?? packageVersion,
    10,
  );

  if (!Number.isNaN(specMajor) && !Number.isNaN(packageMajor) && specMajor !== packageMajor) {
    throw new Error(
      `SDK package major (${packageMajor}) must match OpenAPI major (${specMajor}).`,
    );
  }

  const errors = errorConfig.errorCodes ?? [];
  const errorCodeLiterals = errors.map((entry) => entry.code);
  const statusByCode = Object.fromEntries(errors.map((entry) => [entry.code, entry.httpStatus]));

  writeFileSync(
    metadataPath,
    `export const sdkPackageName = ${JSON.stringify(pkg.name)} as const;\nexport const sdkPackageVersion = ${JSON.stringify(packageVersion)} as const;\nexport const sdkApiVersion = ${JSON.stringify(apiVersion)} as const;\nexport const sdkGeneratedAt = ${JSON.stringify(new Date().toISOString())} as const;\n\nexport const sdkVersionMetadata = {\n  packageName: sdkPackageName,\n  packageVersion: sdkPackageVersion,\n  apiVersion: sdkApiVersion,\n  generatedAt: sdkGeneratedAt,\n} as const;\n\nexport function assertCompatibleApiVersion(actualVersion: string): void {\n  const expectedMajor = sdkApiVersion.split('.')[0];\n  const actualMajor = actualVersion.split('.')[0];\n\n  if (expectedMajor !== actualMajor) {\n    throw new Error(\n      \`Incompatible Nestera API version: expected major \${expectedMajor}, received \${actualVersion}.\`,\n    );\n  }\n}\n`,
    'utf8',
  );

  writeFileSync(
    errorsPath,
    `import type { components } from './generated/schema';\n\nexport type SdkErrorResponse = components['schemas']['StandardErrorResponseDto'];\nexport type ValidationSdkErrorResponse = components['schemas']['ValidationErrorDto'];\nexport type KnownSdkErrorCode = ${errorCodeLiterals.map((code) => `'${code}'`).join(' | ') || 'never'};\n\nexport const sdkErrorStatusByCode = ${toConstObject(statusByCode)} as const;\n\nexport type KnownSdkError = SdkErrorResponse & {\n  errorCode: KnownSdkErrorCode;\n};\n\nexport type SdkErrorByCode = {\n${errorCodeLiterals.map((code) => `  ${JSON.stringify(code)}: SdkErrorResponse & { errorCode: ${JSON.stringify(code)}; statusCode: ${(statusByCode[code] ?? 'number')} };`).join('\n')}\n};\n\nexport type TypedSdkError = SdkErrorByCode[keyof SdkErrorByCode] | ValidationSdkErrorResponse;\n\nexport function isSdkErrorResponse(value: unknown): value is SdkErrorResponse {\n  return Boolean(\n    value &&\n      typeof value === 'object' &&\n      'errorCode' in value &&\n      'message' in value &&\n      'statusCode' in value,\n  );\n}\n\nexport function isTypedSdkError(value: unknown): value is TypedSdkError {\n  if (!isSdkErrorResponse(value)) {\n    return false;\n  }\n\n  return typeof value.errorCode === 'string';\n}\n\nexport function getSdkErrorStatus(errorCode: KnownSdkErrorCode): number {\n  return sdkErrorStatusByCode[errorCode];\n}\n`,
    'utf8',
  );

  writeFileSync(
    indexPath,
    `export * from './generated';\nexport * from './errors';\nexport * from './metadata';\n`,
    'utf8',
  );
}

function runtimeOpenApiSource(specVersion) {
  return `/* generated by sdk/scripts/generate-sdk.mjs */
import type { ApiRequestOptions } from './ApiRequestOptions';

export type Resolver<T> = (options: ApiRequestOptions) => Promise<T> | T;

export type HeadersResolver =
  | Record<string, string>
  | Resolver<Record<string, string>>;

export type TokenResolver = string | Resolver<string | undefined> | undefined;
export type CorrelationIdResolver =
  | string
  | Resolver<string | undefined>
  | undefined;

export interface SdkRequestMiddlewareContext {
  url: string;
  init: RequestInit;
  options: ApiRequestOptions;
  attempt: number;
}

export interface SdkResponseMiddlewareContext extends SdkRequestMiddlewareContext {
  response: Response;
}

export interface SdkErrorMiddlewareContext extends SdkRequestMiddlewareContext {
  error: unknown;
}

export interface SdkMiddleware {
  onRequest?: (
    context: SdkRequestMiddlewareContext,
  ) => Promise<SdkRequestMiddlewareContext | void> | SdkRequestMiddlewareContext | void;
  onResponse?: (
    context: SdkResponseMiddlewareContext,
  ) => Promise<Response | void> | Response | void;
  onError?: (
    context: SdkErrorMiddlewareContext,
  ) => Promise<unknown> | unknown;
}

export interface OpenAPIConfig {
  BASE: string;
  VERSION: string;
  WITH_CREDENTIALS: boolean;
  CREDENTIALS: RequestCredentials;
  TOKEN?: TokenResolver;
  USERNAME?: string | Resolver<string | undefined> | undefined;
  PASSWORD?: string | Resolver<string | undefined> | undefined;
  HEADERS?: HeadersResolver | undefined;
  ENCODE_PATH?: ((path: string) => string) | undefined;
  FETCH?: typeof fetch;
  TIMEOUT_MS?: number;
  RETRY_GET_ATTEMPTS?: number;
  RETRY_GET_STATUSES?: number[];
  CORRELATION_ID?: CorrelationIdResolver;
  MIDDLEWARE?: SdkMiddleware[];
}

export const OpenAPI: OpenAPIConfig = {
  BASE: '',
  VERSION: ${JSON.stringify(specVersion)},
  WITH_CREDENTIALS: false,
  CREDENTIALS: 'include',
  TOKEN: undefined,
  USERNAME: undefined,
  PASSWORD: undefined,
  HEADERS: undefined,
  ENCODE_PATH: undefined,
  FETCH: undefined,
  TIMEOUT_MS: 10000,
  RETRY_GET_ATTEMPTS: 2,
  RETRY_GET_STATUSES: [408, 425, 429, 500, 502, 503, 504],
  CORRELATION_ID: undefined,
  MIDDLEWARE: [],
};
`;
}

function runtimeRequestSource() {
  return `/* generated by sdk/scripts/generate-sdk.mjs */
import { ApiError } from './ApiError';
import type { ApiRequestOptions } from './ApiRequestOptions';
import type { ApiResult } from './ApiResult';
import { CancelablePromise } from './CancelablePromise';
import { OpenAPI } from './OpenAPI';

type Resolver<T> = T | ((options: ApiRequestOptions) => Promise<T> | T);

const isDefined = <T>(value: T | null | undefined): value is Exclude<T, null | undefined> => {
  return value !== undefined && value !== null;
};

const isBlob = (value: unknown): value is Blob =>
  typeof Blob !== 'undefined' && value instanceof Blob;

const isFormData = (value: unknown): value is FormData =>
  typeof FormData !== 'undefined' && value instanceof FormData;

const isString = (value: unknown): value is string => typeof value === 'string';

const isStringWithValue = (value: unknown): value is string =>
  isString(value) && value !== '';

const base64 = (str: string): string => {
  if (typeof btoa !== 'undefined') {
    return btoa(str);
  }

  return Buffer.from(str).toString('base64');
};

const resolve = async <T>(
  options: ApiRequestOptions,
  resolver?: Resolver<T>,
): Promise<T | undefined> => {
  if (typeof resolver === 'function') {
    return await resolver(options);
  }

  return resolver;
};

const getQueryString = (params: Record<string, unknown>): string => {
  const searchParams = new URLSearchParams();

  const append = (key: string, value: unknown): void => {
    if (!isDefined(value)) {
      return;
    }

    if (Array.isArray(value)) {
      value.forEach((item) => append(key, item));
      return;
    }

    if (typeof value === 'object' && !isBlob(value) && !isFormData(value)) {
      Object.entries(value as Record<string, unknown>).forEach(([nestedKey, nestedValue]) => {
        append(`\${key}[\${nestedKey}]`, nestedValue);
      });
      return;
    }

    searchParams.append(key, String(value));
  };

  Object.entries(params).forEach(([key, value]) => append(key, value));
  const query = searchParams.toString();
  return query ? `?\${query}` : '';
};

const getUrl = (config: typeof OpenAPI, options: ApiRequestOptions): string => {
  const encoder = config.ENCODE_PATH ?? encodeURI;
  const path = options.url.replace(/{(.*?)}/g, (substring, group) => {
    if (options.path?.[group] === undefined) {
      return substring;
    }

    return encoder(String(options.path[group]));
  });

  const url = `\${config.BASE}\${path}`;
  if (options.query) {
    return `\${url}\${getQueryString(options.query as Record<string, unknown>)}`;
  }

  return url;
};

const getFormData = (options: ApiRequestOptions): FormData | undefined => {
  if (!options.formData) {
    return undefined;
  }

  const formData = new FormData();
  const append = (key: string, value: unknown): void => {
    if (!isDefined(value)) {
      return;
    }

    if (Array.isArray(value)) {
      value.forEach((item) => append(key, item));
      return;
    }

    if (isBlob(value) || isString(value)) {
      formData.append(key, value);
      return;
    }

    formData.append(key, JSON.stringify(value));
  };

  Object.entries(options.formData).forEach(([key, value]) => append(key, value));
  return formData;
};

const getRequestBody = (options: ApiRequestOptions): BodyInit | undefined => {
  if (options.body === undefined) {
    return undefined;
  }

  if (options.mediaType?.includes('application/json')) {
    return JSON.stringify(options.body);
  }

  if (
    options.mediaType?.includes('application/octet-stream') ||
    options.mediaType?.includes('multipart/form-data') ||
    isBlob(options.body) ||
    isFormData(options.body)
  ) {
    return options.body as BodyInit;
  }

  if (typeof options.body === 'string') {
    return options.body;
  }

  return JSON.stringify(options.body);
};

const getHeaders = async (options: ApiRequestOptions): Promise<Headers> => {
  const token = await resolve(options, OpenAPI.TOKEN);
  const username = await resolve(options, OpenAPI.USERNAME);
  const password = await resolve(options, OpenAPI.PASSWORD);
  const additionalHeaders = await resolve(options, OpenAPI.HEADERS);
  const correlationId = await resolve(options, OpenAPI.CORRELATION_ID);

  const headers = new Headers({
    Accept: 'application/json',
    ...additionalHeaders,
    ...options.headers,
  });

  if (isStringWithValue(token)) {
    headers.set('Authorization', `Bearer \${token}`);
  }

  if (isStringWithValue(username) && isStringWithValue(password)) {
    headers.set('Authorization', `Basic \${base64(`\${username}:\${password}`)}`);
  }

  if (isStringWithValue(correlationId) && !headers.has('X-Correlation-Id')) {
    headers.set('X-Correlation-Id', correlationId);
  }

  const body = getRequestBody(options);
  const formData = getFormData(options);

  if (body !== undefined && !formData && options.mediaType && !headers.has('Content-Type')) {
    headers.set('Content-Type', options.mediaType);
  }

  return headers;
};

const sleep = async (ms: number): Promise<void> => {
  await new Promise((resolvePromise) => {
    setTimeout(resolvePromise, ms);
  });
};

const shouldRetry = (
  options: ApiRequestOptions,
  result: ApiResult | undefined,
  error: unknown,
  attempt: number,
): boolean => {
  const allowedAttempts = OpenAPI.RETRY_GET_ATTEMPTS ?? 0;
  if (options.method.toUpperCase() !== 'GET' || attempt >= allowedAttempts) {
    return false;
  }

  if (error instanceof Error && error.name === 'AbortError') {
    return true;
  }

  const statuses = OpenAPI.RETRY_GET_STATUSES ?? [];
  return Boolean(result && statuses.includes(result.status));
};

const sendRequest = async (
  options: ApiRequestOptions,
  url: string,
  init: RequestInit,
): Promise<Response> => {
  const fetchClient = OpenAPI.FETCH ?? fetch;
  const timeoutMs = OpenAPI.TIMEOUT_MS ?? 10000;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    return await fetchClient(url, {
      ...init,
      signal: controller.signal,
    });
  } finally {
    clearTimeout(timeout);
  }
};

const getResponseBody = async (response: Response): Promise<unknown> => {
  if (response.status === 204) {
    return undefined;
  }

  const contentType = response.headers.get('Content-Type') ?? '';
  if (contentType.includes('application/json')) {
    return await response.json();
  }

  if (
    contentType.includes('application/octet-stream') ||
    contentType.includes('application/pdf') ||
    contentType.includes('image/') ||
    contentType.includes('text/csv')
  ) {
    return await response.blob();
  }

  const text = await response.text();
  return text.length > 0 ? text : undefined;
};

const getResponseHeader = (
  response: Response,
  responseHeader?: string,
): string | null | undefined => {
  if (!responseHeader) {
    return undefined;
  }

  return response.headers.get(responseHeader);
};

const catchErrorCodes = (options: ApiRequestOptions, result: ApiResult): void => {
  const errors: Record<number, string> = {
    400: 'Bad Request',
    401: 'Unauthorized',
    403: 'Forbidden',
    404: 'Not Found',
    409: 'Conflict',
    413: 'Payload Too Large',
    422: 'Unprocessable Entity',
    429: 'Too Many Requests',
    500: 'Internal Server Error',
    502: 'Bad Gateway',
    503: 'Service Unavailable',
    504: 'Gateway Timeout',
    ...options.errors,
  };

  const error = errors[result.status];
  if (error) {
    throw new ApiError(options, result, error);
  }

  if (!result.ok) {
    throw new ApiError(options, result, 'Generic Error');
  }
};

export const request = <T>(
  options: ApiRequestOptions,
): CancelablePromise<T> => {
  return new CancelablePromise(async (resolvePromise, rejectPromise, onCancel) => {
    let canceled = false;
    onCancel(() => {
      canceled = true;
    });

    for (let attempt = 0; ; attempt += 1) {
      try {
        const url = getUrl(OpenAPI, options);
        const formData = getFormData(options);
        const body = formData ?? getRequestBody(options);
        const headers = await getHeaders(options);

        let requestContext = {
          url,
          options,
          attempt,
          init: {
            method: options.method,
            headers,
            body,
            credentials: OpenAPI.WITH_CREDENTIALS
              ? OpenAPI.CREDENTIALS
              : 'same-origin',
          } satisfies RequestInit,
        };

        for (const middleware of OpenAPI.MIDDLEWARE ?? []) {
          if (middleware.onRequest) {
            const updatedContext = await middleware.onRequest(requestContext);
            if (updatedContext) {
              requestContext = updatedContext;
            }
          }
        }

        if (canceled) {
          return;
        }

        let response = await sendRequest(
          options,
          requestContext.url,
          requestContext.init,
        );

        for (const middleware of OpenAPI.MIDDLEWARE ?? []) {
          if (middleware.onResponse) {
            const updatedResponse = await middleware.onResponse({
              ...requestContext,
              response,
            });
            if (updatedResponse) {
              response = updatedResponse;
            }
          }
        }

        const responseBody = await getResponseBody(response);
        const responseHeader = getResponseHeader(response, options.responseHeader);
        const result: ApiResult = {
          url: requestContext.url,
          ok: response.ok,
          status: response.status,
          statusText: response.statusText,
          body: responseHeader ?? responseBody,
        };

        if (shouldRetry(options, result, undefined, attempt)) {
          await sleep(150 * (attempt + 1));
          continue;
        }

        catchErrorCodes(options, result);
        resolvePromise(result.body as T);
        return;
      } catch (error) {
        let finalError = error;

        const requestContext = {
          url: getUrl(OpenAPI, options),
          options,
          attempt,
          init: {
            method: options.method,
          } satisfies RequestInit,
        };

        for (const middleware of OpenAPI.MIDDLEWARE ?? []) {
          if (middleware.onError) {
            const maybeReplacement = await middleware.onError({
              ...requestContext,
              error: finalError,
            });
            if (maybeReplacement !== undefined) {
              finalError = maybeReplacement;
            }
          }
        }

        if (shouldRetry(options, undefined, finalError, attempt)) {
          await sleep(150 * (attempt + 1));
          continue;
        }

        rejectPromise(finalError);
        return;
      }
    }
  });
};
`;
}

function main() {
  const spec = readJson(openApiPath);
  const pkg = readJson(packageJsonPath);
  const errorConfig = readJson(errorCodesPath);

  rmSync(generatedRoot, { recursive: true, force: true });
  mkdirSync(generatedRoot, { recursive: true });

  execFileSync(
    process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm',
    [
      'exec',
      'openapi',
      '--input',
      openApiPath,
      '--output',
      generatedRoot,
      '--client',
      'fetch',
      '--useUnionTypes',
      '--exportCore',
      'true',
      '--exportServices',
      'true',
      '--exportModels',
      'true',
      '--exportSchemas',
      'true',
      '--indent',
      '2',
    ],
    {
      cwd: sdkRoot,
      stdio: 'inherit',
    },
  );

  writeFileSync(
    path.join(generatedRoot, 'core', 'OpenAPI.ts'),
    runtimeOpenApiSource(String(spec.info?.version ?? '2.0.0')),
    'utf8',
  );

  writeFileSync(
    path.join(generatedRoot, 'core', 'request.ts'),
    runtimeRequestSource(),
    'utf8',
  );

  writeRuntimeFiles(spec, pkg, errorConfig);
}

main();
